diffbot_base_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    left_wheel_names: ["left_wheel_link"]
    right_wheel_names: ["right_wheel_link"]
    wheel_separation: 0.4
    wheel_radius: 0.05
    cmd_vel_timeout: 0.5
    use_stamped_vel: false
    enable_odom_tf: true
    publish_rate: 50
