<?xml version="1.0"?>
<!-- Fixed: Added robot name and ensured joint uniqueness.
           Fixed wheel joint origins for proper ground clearance.
           Fixed LIDAR sensor placement inside the <gazebo reference> block.
-->
<robot name="complex_differential_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- ========================== -->
    <!-- ROBOT PROPERTIES -->
    <!-- ========================== -->
    <xacro:property name="base_length" value="0.6"/>
    <xacro:property name="base_width" value="0.4"/>
    <xacro:property name="base_height" value="0.2"/>
    <xacro:property name="wheel_radius" value="0.1"/>
    <xacro:property name="wheel_length" value="0.05"/>
    <xacro:property name="caster_radius" value="0.05"/>
    <xacro:property name="pi" value="3.14159265359"/>

    <!-- Flap/Finger dimensions -->
    <xacro:property name="finger_length" value="0.2"/>
    <xacro:property name="finger_width" value="0.03"/>
    <xacro:property name="finger_height" value="0.08"/>

    <!-- LIDAR dimensions and mounting height -->
    <xacro:property name="lidar_radius" value="0.07"/>
    <xacro:property name="lidar_length" value="0.04"/>
    <xacro:property name="lidar_height_offset" value="${base_height/2.0 + 0.15}"/>
    
    <!-- Control Parameters -->
    <xacro:property name="max_linear_acceleration" value="10"/>
    <xacro:property name="wheel_separation" value="${base_width + wheel_length}"/>

    <!-- ========================== -->
    <!-- MATERIALS (For Gazebo Visuals) -->
    <!-- ========================== -->
    <material name="blue">
        <color rgba="0.0 0.0 0.8 1.0"/>
    </material>
    <material name="grey">
        <color rgba="0.7 0.7 0.7 1.0"/>
    </material>
    <material name="red">
        <color rgba="0.8 0.0 0.0 1.0"/>
    </material>


    <!-- ========================== -->
    <!-- WORLD + BASE LINK -->
    <!-- ========================== -->
    <link name="base_footprint"/>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <!-- Center of box relative to link frame -->
            <origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0"/>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0"/>
        </collision>
        <inertial>
            <mass value="5.0"/>
            <origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0"/>
            <inertia ixx="0.1" iyy="0.1" izz="0.1" ixy="0" ixz="0" iyz="0"/>
        </inertial>
    </link>

    <!-- Joint connecting base_footprint and base_link to elevate the robot -->
    <!-- Renamed from 'base_joint' to 'robot_base_joint' to avoid uniqueness conflict -->
    <joint name="robot_base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <!-- Rises the base so wheel bottom is at z=0 (ground level) -->
        <origin xyz="0 0 ${wheel_radius}"/>
    </joint>

    <!-- ========================== -->
    <!-- WHEEL MACRO -->
    <!-- ========================== -->
    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <material name="grey"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            </collision>
            <inertial>
                <mass value="0.2"/>
                <origin xyz="0 0 0"/>
                <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
            </inertial>
        </link>
        
        <!-- Gazebo properties for friction/surface -->
        <gazebo reference="${prefix}_wheel_link">
            <mu1>1.0</mu1>
            <mu2>1.0</mu2>
        </gazebo>
    </xacro:macro>

    <xacro:wheel_link prefix="right"/>
    <xacro:wheel_link prefix="left"/>

    <!-- ========================== -->
    <!-- CASTER WHEEL -->
    <!-- ========================== -->
    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
            <material name="grey"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.05"/>
            <origin xyz="0 0 0"/>
            <inertia ixx="0.0005" iyy="0.0005" izz="0.0005" ixy="0" ixz="0" iyz="0"/>
        </inertial>
    </link>

    <!-- Gazebo properties for caster (near zero friction) -->
    <gazebo reference="caster_wheel_link">
        <mu1>0.000001</mu1>
        <mu2>0.000001</mu2>
    </gazebo>

    <!-- ========================== -->
    <!-- FLAPS / FINGERS -->
    <!-- ========================== -->
    <!-- LEFT FLAP -->
    <link name="left_flap_link">
        <visual>
            <geometry>
                <box size="${finger_length} ${finger_width} ${finger_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0.2"/>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <box size="${finger_length} ${finger_width} ${finger_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0.2"/>
        </collision>
        <inertial>
            <mass value="0.07"/>
            <origin xyz="${finger_length/2} ${finger_width/2} ${finger_height/2}"/>
            <inertia ixx="0.00005" iyy="0.00005" izz="0.00006" ixy="0" ixz="0" iyz="0"/>
        </inertial>
    </link>

    <!-- RIGHT FLAP -->
    <link name="right_flap_link">
        <visual>
            <geometry>
                <box size="${finger_length} ${finger_width} ${finger_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 -0.2"/>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <box size="${finger_length} ${finger_width} ${finger_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 -0.2"/>
        </collision>
        <inertial>
            <mass value="0.07"/>
            <origin xyz="${finger_length/2} ${finger_width/2} ${finger_height/2}"/>
            <inertia ixx="0.00005" iyy="0.00005" izz="0.00006" ixy="0" ixz="0" iyz="0"/>
        </inertial>
    </link>

    <!-- ========================== -->
    <!-- LIDAR -->
    <!-- ========================== -->
    <link name="lidar_link">
        <visual>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
            </geometry>
            <material name="grey"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
            </geometry>
            <origin xyz="0 0 0"/>
        </collision>
        <inertial>
            <mass value="0.1"/>
            <origin xyz="0 0 0"/>
            <inertia ixx="0.0005" ixy="0" ixz="0" iyy="0.0005" iyz="0" izz="0.0005"/>
        </inertial>
    </link>
    
    <!-- Gazebo sensor definition attached directly to the link -->
    <gazebo reference="lidar_link">
        <sensor name="laser_sensor" type="gpu_lidar">
            <topic>lidar</topic>
            <pose>0 0 0 0 0 0</pose> <!-- Relative to lidar_link -->
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>640</samples>
                        <resolution>1</resolution>
                        <min_angle>-2.2689</min_angle> <!-- -130 deg -->
                        <max_angle>2.2689</max_angle>  <!-- +130 deg -->
                    </horizontal>
                </scan>
                <range>
                    <min>0.1</min>
                    <max>10.0</max>
                    <resolution>0.01</resolution>
                </range>
            </ray>
            <always_on>1</always_on>
            <visualize>true</visualize>
        </sensor>
    </gazebo>

    <!-- ========================== -->
    <!-- JOINTS -->
    <!-- ========================== -->

    <!-- Wheel joints (Continuous for rotation) -->
    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <!-- Positioned at z=0 relative to base_link's frame (which is raised by wheel_radius) -->
        <origin xyz="${-base_length/4} ${-wheel_separation/2} 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <!-- Positioned at z=0 relative to base_link's frame (which is raised by wheel_radius) -->
        <origin xyz="${-base_length/4} ${wheel_separation/2} 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <!-- Caster wheel joint (Fixed for stability, using a frictionless sphere) -->
    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel_link"/>
        <!-- Positions the caster so its bottom is at z=0 (ground) -->
        <origin xyz="${base_length/3} 0 ${-(wheel_radius - caster_radius)}"/>
    </joint>

    <!-- LEFT FLAP JOINT (Revolute for movement) -->
    <joint name="left_flap_joint" type="revolute">
        <parent link="base_link"/>
        <child link="left_flap_link"/>
        <origin xyz="${base_length/2 + finger_length/2} ${base_width/4} ${finger_height/2}" rpy="0 0 0"/>
        <axis xyz="0 0 -1"/>
        <limit lower="0" upper="1.2" effort="10" velocity="1.5"/>
    </joint>

    <!-- RIGHT FLAP JOINT (Revolute for movement) -->
    <joint name="right_flap_joint" type="revolute">
        <parent link="base_link"/>
        <child link="right_flap_link"/>
        <origin xyz="${base_length/2 + finger_length/2} ${-base_width/4} ${finger_height/2}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="0" upper="1.2" effort="10" velocity="1.5"/>
    </joint>

    <!-- LIDAR JOINT (Fixed to the top of the base) -->
    <joint name="lidar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="lidar_link"/>
        <origin xyz="0 0 ${lidar_height_offset}"/>
    </joint>

    <!-- ========================== -->
    <!-- GAZEBO PLUGINS (CONTROLLERS) -->
    <!-- ========================== -->
    <gazebo>
        <!-- 1. Differential Drive Plugin (Handles cmd_vel subscription and odometry publishing) -->
        <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">
            <right_joint>base_right_wheel_joint</right_joint>
            <left_joint>base_left_wheel_joint</left_joint>
            <wheel_separation>${wheel_separation}</wheel_separation>
            <wheel_radius>${wheel_radius}</wheel_radius>
            <max_linear_acceleration>${max_linear_acceleration}</max_linear_acceleration>
            <odom_publish_frequency>100</odom_publish_frequency>
            <topic>cmd_vel</topic>
            <odom_topic>odom</odom_topic>
        </plugin>

        <!-- 2. Joint State Publisher Plugin (Publishes all joint states for ROS visualization) -->
        <plugin filename="gz-sim-joint-state-publisher-system" name="gz::sim::systems::JointStatePublisher">
            <topic>joint_states</topic>
            <joint_name>base_right_wheel_joint</joint_name>
            <joint_name>base_left_wheel_joint</joint_name>
            <joint_name>left_flap_joint</joint_name>
            <joint_name>right_flap_joint</joint_name>
        </plugin>

        <!-- 3. Position Controller for Left Flap -->
        <plugin filename="gz-sim-joint-controller-system" name="left_flap_controller">
            <joint_name>left_flap_joint</joint_name>
            <!-- Topic must be bridged from ROS 2 using gz.msgs.Double -->
            <topic>left_flap_controller/cmd_pos</topic>
        </plugin>

        <!-- 4. Position Controller for Right Flap -->
        <plugin filename="gz-sim-joint-controller-system" name="right_flap_controller">
            <joint_name>right_flap_joint</joint_name>
            <!-- Topic must be bridged from ROS 2 using gz.msgs.Double -->
            <topic>right_flap_controller/cmd_pos</topic>
        </plugin>
    </gazebo>
</robot>