<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Parameters -->
    <xacro:property name="base_length" value="0.6"/>
    <xacro:property name="base_width" value="0.4"/>
    <xacro:property name="base_height" value="0.2"/>
    <xacro:property name="wheel_radius" value="0.1"/>
    <xacro:property name="wheel_length" value="0.05"/>

    <!-- Root link MUST have inertia for Gazebo -->
    <link name="base_footprint">
        <inertial>
            <mass value="0.01"/>
            <origin xyz="0 0 0"/>
            <inertia ixx="1e-4" ixy="0" ixz="0"
                     iyy="1e-4" iyz="0"
                     izz="1e-4"/>
        </inertial>
    </link>

    <!-- Base link -->
    <link name="base_link">
        <inertial>
            <mass value="5.0"/>
            <origin xyz="0 0 0"/>
            <inertia ixx="0.03" ixy="0" ixz="0"
                     iyy="0.03" iyz="0"
                     izz="0.03"/>
        </inertial>

        <visual>
            <origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0"/>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name="blue" />
        </visual>

        <collision>
            <origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0"/>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
        </collision>
    </link>

    <!-- Wheel macro (with inertia + collision) -->
    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">

            <inertial>
                <mass value="0.2"/>
                <origin xyz="0 0 0"/>
                <inertia ixx="0.001" ixy="0" ixz="0"
                         iyy="0.001" iyz="0"
                         izz="0.001"/>
            </inertial>

            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <material name="grey" />
            </visual>

            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            </collision>

        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="right"/>
    <xacro:wheel_link prefix="left"/>

    <!-- Caster -->
    <link name="caster_wheel_link">
        <inertial>
            <mass value="0.05"/>
            <origin xyz="0 0 0"/>
            <inertia ixx="5e-4" ixy="0" ixz="0"
                     iyy="5e-4" iyz="0"
                     izz="5e-4"/>
        </inertial>

        <visual>
            <geometry>
                <sphere radius="${wheel_radius/2.0}"/>
            </geometry>
            <origin xyz="0 0 0"/>
            <material name="grey"/>
        </visual>

        <collision>
            <geometry>
                <sphere radius="${wheel_radius/2.0}"/>
            </geometry>
            <origin xyz="0 0 0"/>
        </collision>
    </link>

    <!-- Joints -->
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="${-base_length/4.0} ${-(base_width + wheel_length)/2.0} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="${-base_length/4.0} ${(base_width + wheel_length)/2.0} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel_link"/>
        <origin xyz="${base_length/3.0} 0 ${-wheel_radius/2.0}" rpy="0 0 0"/>
    </joint>

</robot>
