<?xml version="1.0"?>
<robot name="flap_tb3_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- ========================== -->
  <!-- PROPERTIES (SCALED UP)    -->
  <!-- ========================== -->
  <!-- Robot size increased ~30% -->
  <xacro:property name="base_length" value="0.75"/>
  <xacro:property name="base_width"  value="0.55"/>
  <xacro:property name="base_height" value="0.25"/>

  <xacro:property name="wheel_radius"  value="0.12"/>
  <xacro:property name="wheel_length"  value="0.06"/>
  <xacro:property name="caster_radius" value="0.06"/>
  <xacro:property name="pi" value="3.14159265359"/>

  <!-- Flap (finger) dimensions - LONGER + WIDER -->
  <xacro:property name="finger_length" value="0.40"/>  <!-- was 0.2 -->
  <xacro:property name="finger_width"  value="0.06"/>  <!-- was 0.03 -->
  <xacro:property name="finger_height" value="0.10"/>  <!-- slightly taller -->

  <!-- LIDAR dimensions (slightly larger) -->
  <xacro:property name="lidar_radius"        value="0.08"/>
  <xacro:property name="lidar_length"        value="0.05"/>
  <xacro:property name="lidar_height_offset" value="${base_height/2.0 + 0.18}"/>

  <!-- Control -->
  <xacro:property name="max_linear_acceleration" value="10"/>
  <xacro:property name="wheel_separation" value="${base_width + wheel_length}"/>

  <!-- ========================== -->
  <!-- MATERIALS                  -->
  <!-- ========================== -->
  <material name="blue">
    <color rgba="0.0 0.0 0.8 1.0"/>
  </material>
  <material name="grey">
    <color rgba="0.7 0.7 0.7 1.0"/>
  </material>
  <material name="red">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>

  <!-- ========================== -->
  <!-- BASE & FOOTPRINT           -->
  <!-- ========================== -->
  <link name="base_footprint"/>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0"/>
      <mass value="7.0"/>
      <inertia ixx="0.2" iyy="0.2" izz="0.2" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <!-- Raise base so wheels touch ground -->
  <joint name="robot_base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_radius}"/>
  </joint>

  <!-- ========================== -->
  <!-- WHEEL MACRO                -->
  <!-- ========================== -->
  <xacro:macro name="wheel_link" params="prefix">
    <link name="${prefix}_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        <material name="grey"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0"/>
        <mass value="0.3"/>
        <inertia ixx="0.002" iyy="0.002" izz="0.002" ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>

    <gazebo reference="${prefix}_wheel_link">
      <mu1>1.0</mu1>
      <mu2>1.0</mu2>
    </gazebo>
  </xacro:macro>

  <xacro:wheel_link prefix="right"/>
  <xacro:wheel_link prefix="left"/>

  <!-- ========================== -->
  <!-- CASTER WHEEL               -->
  <!-- ========================== -->
  <link name="caster_wheel_link">
    <visual>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="0.07"/>
      <inertia ixx="0.0007" iyy="0.0007" izz="0.0007" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <gazebo reference="caster_wheel_link">
    <mu1>0.000001</mu1>
    <mu2>0.000001</mu2>
  </gazebo>

  <!-- ========================== -->
  <!-- FLAPS / FINGERS (WIDER)    -->
  <!-- ========================== -->
  <link name="left_flap_link">
    <visual>
      <!-- rotated slightly outward (counter-clockwise) -->
      <origin xyz="0 0 0" rpy="0 0 0.25"/>
      <geometry>
        <box size="${finger_length} ${finger_width} ${finger_height}"/>
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0.25"/>
      <geometry>
        <box size="${finger_length} ${finger_width} ${finger_height}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="${finger_length/2} 0 ${finger_height/2}"/>
      <mass value="0.10"/>
      <inertia ixx="0.00008" iyy="0.00008" izz="0.00009" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <link name="right_flap_link">
    <visual>
      <!-- rotated slightly outward (clockwise) -->
      <origin xyz="0 0 0" rpy="0 0 -0.25"/>
      <geometry>
        <box size="${finger_length} ${finger_width} ${finger_height}"/>
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 -0.25"/>
      <geometry>
        <box size="${finger_length} ${finger_width} ${finger_height}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="${finger_length/2} 0 ${finger_height/2}"/>
      <mass value="0.10"/>
      <inertia ixx="0.00008" iyy="0.00008" izz="0.00009" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <!-- ========================== -->
  <!-- LIDAR                      -->
  <!-- ========================== -->
  <link name="lidar_link">
    <visual>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
      </geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0"/>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="0.15"/>
      <inertia ixx="0.0007" iyy="0.0007" izz="0.0007" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <!-- LIDAR sensor: Laser system, frame_id = lidar_link -->
  <gazebo reference="lidar_link">
    <sensor name="laser_sensor" type="ray">
      <pose>0 0 0 0 0 0</pose>
      <update_rate>10</update_rate>

      <ray>
        <scan>
          <horizontal>
            <samples>640</samples>
            <resolution>1</resolution>
            <min_angle>-2.2689</min_angle>
            <max_angle> 2.2689</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.1</min>
          <max>10.0</max>
          <resolution>0.01</resolution>
        </range>
      </ray>

      <always_on>1</always_on>
      <visualize>true</visualize>

      <plugin
        filename="gz-sim-laser-system"
        name="gz::sim::systems::Laser">
        <topic>lidar</topic>
        <frame_id>lidar_link</frame_id>
      </plugin>
    </sensor>
  </gazebo>

  <!-- ========================== -->
  <!-- JOINTS                     -->
  <!-- ========================== -->

  <!-- Wheels -->
  <joint name="base_right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel_link"/>
    <origin xyz="${-base_length/4} ${-wheel_separation/2} 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <joint name="base_left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel_link"/>
    <origin xyz="${-base_length/4} ${wheel_separation/2} 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Caster -->
  <joint name="base_caster_wheel_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_wheel_link"/>
    <origin xyz="${base_length/3} 0 ${-(wheel_radius - caster_radius)}"/>
  </joint>

  <!-- Flaps
       NOTE: y = +/- (base_width/2 - finger_width/2)
       so the flaps sit almost at the outer edges, giving more useful width.
       Limits remain 0..1.2 rad so teleop code does NOT need changes.
  -->
  <joint name="left_flap_joint" type="revolute">
    <parent link="base_link"/>
    <child link="left_flap_link"/>
    <origin
      xyz="${base_length/2 + finger_length/2} ${base_width/2 - finger_width/2} ${finger_height/2}"
      rpy="0 0 0"/>
    <axis xyz="0 0 -1"/>
    <limit lower="0" upper="1.2" effort="10" velocity="1.5"/>
  </joint>

  <joint name="right_flap_joint" type="revolute">
    <parent link="base_link"/>
    <child link="right_flap_link"/>
    <origin
      xyz="${base_length/2 + finger_length/2} ${-(base_width/2 - finger_width/2)} ${finger_height/2}"
      rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="0" upper="1.2" effort="10" velocity="1.5"/>
  </joint>

  <!-- LIDAR joint -->
  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="0 0 ${lidar_height_offset}"/>
  </joint>

  <!-- ========================== -->
  <!-- GAZEBO PLUGINS             -->
  <!-- ========================== -->
  <gazebo>

    <!-- Diff drive plugin (wheels) -->
    <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">
      <right_joint>base_right_wheel_joint</right_joint>
      <left_joint>base_left_wheel_joint</left_joint>
      <wheel_separation>${wheel_separation}</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>
      <max_linear_acceleration>${max_linear_acceleration}</max_linear_acceleration>
      <odom_publish_frequency>100</odom_publish_frequency>
      <topic>cmd_vel</topic>
      <odom_topic>odom</odom_topic>
    </plugin>

    <!-- Joint state publisher -->
    <plugin filename="gz-sim-joint-state-publisher-system" name="gz::sim::systems::JointStatePublisher">
      <topic>joint_states</topic>
      <joint_name>base_right_wheel_joint</joint_name>
      <joint_name>base_left_wheel_joint</joint_name>
      <joint_name>left_flap_joint</joint_name>
      <joint_name>right_flap_joint</joint_name>
    </plugin>

    <!-- Flap position controllers (topics unchanged) -->
    <plugin
      filename="gz-sim-joint-position-controller-system"
      name="gz::sim::systems::JointPositionController">
      <joint_name>left_flap_joint</joint_name>
      <topic>left_flap_controller/cmd_pos</topic>
      <p_gain>50.0</p_gain>
    </plugin>

    <plugin
      filename="gz-sim-joint-position-controller-system"
      name="gz::sim::systems::JointPositionController">
      <joint_name>right_flap_joint</joint_name>
      <topic>right_flap_controller/cmd_pos</topic>
      <p_gain>50.0</p_gain>
    </plugin>

  </gazebo>
</robot>
