<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- ========================== -->
    <!-- ROBOT PROPERTIES -->
    <!-- ========================== -->
    <xacro:property name="base_length" value="0.6"/>
    <xacro:property name="base_width" value="0.4"/>
    <xacro:property name="base_height" value="0.2"/>
    <xacro:property name="wheel_radius" value="0.1"/>
    <xacro:property name="wheel_length" value="0.05"/>
    <xacro:property name="caster_radius" value="0.05"/>

    <!-- Flap/Finger dimensions -->
    <xacro:property name="finger_length" value="0.2"/>
    <xacro:property name="finger_width" value="0.03"/>
    <xacro:property name="finger_height" value="0.08"/>

    <!-- LIDAR dimensions -->
    <xacro:property name="lidar_radius" value="0.07"/>
    <xacro:property name="lidar_length" value="0.04"/>
    <xacro:property name="lidar_height" value="${base_height + 0.05}"/>

    <!-- ========================== -->
    <!-- WORLD + BASE LINK -->
    <!-- ========================== -->
    <link name="base_footprint"/>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0"/>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0"/>
        </collision>
        <inertial>
            <mass value="5.0"/>
            <origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0"/>
            <inertia ixx="0.1" iyy="0.1" izz="0.1" ixy="0" ixz="0" iyz="0"/>
        </inertial>
    </link>

    <!-- ========================== -->
    <!-- WHEEL MACRO -->
    <!-- ========================== -->
    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <material name="grey"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            </collision>
            <inertial>
                <mass value="0.2"/>
                <origin xyz="0 0 0"/>
                <inertia ixx="0.001" iyy="0.001" izz="0.001" ixy="0" ixz="0" iyz="0"/>
            </inertial>
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="right"/>
    <xacro:wheel_link prefix="left"/>

    <!-- ========================== -->
    <!-- CASTER WHEEL -->
    <!-- ========================== -->
    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
            <material name="grey"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.05"/>
            <origin xyz="0 0 0"/>
            <inertia ixx="0.0005" iyy="0.0005" izz="0.0005" ixy="0" ixz="0" iyz="0"/>
        </inertial>
    </link>

    <!-- ========================== -->
    <!-- FLAPS / FINGERS -->
    <!-- ========================== -->
    <!-- LEFT FLAP -->
    <link name="left_flap_link">
        <visual>
            <geometry>
                <box size="${finger_length} ${finger_width} ${finger_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0.2"/>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <box size="${finger_length} ${finger_width} ${finger_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0.2"/>
        </collision>
        <inertial>
            <mass value="0.07"/>
            <origin xyz="${finger_length/2} ${finger_width/2} ${finger_height/2}"/>
            <inertia ixx="0.00005" iyy="0.00005" izz="0.00006" ixy="0" ixz="0" iyz="0"/>
        </inertial>
    </link>

    <!-- RIGHT FLAP -->
    <link name="right_flap_link">
        <visual>
            <geometry>
                <box size="${finger_length} ${finger_width} ${finger_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 -0.2"/>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <box size="${finger_length} ${finger_width} ${finger_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 -0.2"/>
        </collision>
        <inertial>
            <mass value="0.07"/>
            <origin xyz="${finger_length/2} ${finger_width/2} ${finger_height/2}"/>
            <inertia ixx="0.00005" iyy="0.00005" izz="0.00006" ixy="0" ixz="0" iyz="0"/>
        </inertial>
    </link>

    <!-- ========================== -->
    <!-- LIDAR -->
    <!-- ========================== -->
    <link name="lidar_link">
        <visual>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
            </geometry>
            <material name="grey"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
            </geometry>
            <origin xyz="0 0 0"/>
        </collision>
        <inertial>
            <mass value="0.1"/>
            <origin xyz="0 0 0"/>
            <inertia ixx="0.0005" iyy="0.0005" izz="0.0005" ixy="0" ixz="0" iyz="0"/>
        </inertial>
    </link>

    <!-- ========================== -->
    <!-- JOINTS -->
    <!-- ========================== -->
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${wheel_radius}"/>
    </joint>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="${-base_length/4} ${-(base_width+wheel_length)/2} 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="${-base_length/4} ${(base_width+wheel_length)/2} 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel_link"/>
        <origin xyz="${base_length/3} 0 ${-wheel_radius/2}"/>
    </joint>

    <!-- LEFT FLAP JOINT -->
    <joint name="left_flap_joint" type="revolute">
        <parent link="base_link"/>
        <child link="left_flap_link"/>
        <origin xyz="${base_length/2 + finger_length/2} ${base_width/4} ${finger_height/2}" rpy="0 0 0"/>
        <axis xyz="0 0 -1"/>
        <limit lower="0" upper="1.2" effort="10" velocity="1.5"/>
    </joint>

    <!-- RIGHT FLAP JOINT -->
    <joint name="right_flap_joint" type="revolute">
        <parent link="base_link"/>
        <child link="right_flap_link"/>
        <origin xyz="${base_length/2 + finger_length/2} ${-base_width/4} ${finger_height/2}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="0" upper="1.2" effort="10" velocity="1.5"/>
    </joint>

    <!-- LIDAR JOINT -->
    <joint name="lidar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="lidar_link"/>
        <origin xyz="0 0 ${lidar_height}"/>
    </joint>

</robot>
